--SORU1) ADI A ÝLE BASLAYAN KÝSÝLERÝ LÝSTELEYÝN
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%'


--2
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' AND GENDER = 'E'

--3
SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '1990-01-01' AND '1995-12-31'
SELECT * FROM CUSTOMERS WHERE BIRTHDATE >= '1990-01-01' AND BIRTHDATE <= '1995-12-31'
SELECT YEAR('1990-01-01') AS YIL
SELECT DATEPART(MONTH,'1990-05-01') AS AY
SELECT * FROM CUSTOMERS WHERE DATEPART(YEAR,BIRTHDATE) >='1990' AND DATEPART(YEAR, BIRTHDATE) <='1995'

--4 JOIN ÝSLEMLERÝ
SELECT C.*, CT.CITY FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID = CT.ID
WHERE CT.CITY = 'ÝSTANBUL'

SELECT C.*, CT.CITY FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID = CT.ID
WHERE CT.CITY IN('ÝSTANBUL','ADANA')

SELECT * FROM CITIES CT 
INNER JOIN DISTRICTS D ON CT.ID = D.CITYID
WHERE CT.CITY = 'ÝSTANBUL'

-- 5 SUBQUERY
SELECT
(SELECT CITY FROM CITIES WHERE ID = C.CITYID),
* FROM CUSTOMERS AS C
WHERE (SELECT CITY FROM CITIES WHERE ID = C.CITYID) = 'ÝSTANBUL'

SELECT 
* FROM CUSTOMERS C
WHERE C.CITYID IN
(SELECT ID FROM CITIES WHERE CITY IN ('ÝSTANBUL','ADANA'))

-- 6) HANGÝ SEHÝRDE KAC MUSTERÝ VAR?
SELECT CT.CITY, COUNT(C.ID) AS TOPLAMMUSTERI FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITY

SELECT *,
(SELECT COUNT(*) FROM CUSTOMERS  WHERE CITYID = CT.ID) AS TOPLAMMUSTERI
FROM CITIES CT
ORDER BY 3

SELECT CT.CITY, COUNT(C.ID) AS TOPLAMMUSTERI FROM CUSTOMERS C
RIGHT JOIN CITIES CT ON C.CITYID = CT.ID
GROUP BY CT.CITY

--7 HER ILDEN KAC MUSTERI VAR ONU BUL VE 10DAN BUYUK OLSUN MUSTERI SAYISI
SELECT CT.CITY, COUNT(C.ID) AS TOPLAMMUSTERI FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITY
HAVING COUNT(C.ID) >=10
ORDER BY 2 DESC

--SUBQUERY
SELECT *,
(SELECT COUNT(*)  FROM CUSTOMERS WHERE C.ID = CITYID)
FROM CITIES C
WHERE (SELECT COUNT(*) FROM CUSTOMERS WHERE C.ID = CITYID) >10
ORDER BY 3 DESC

--8 HANGI SEHIRDE KAC ERKEK KAC KADIN VAR TOPLAMINI VERSIN
SELECT CT.CITY, COUNT(C.ID) AS TOPLAMMUSTERI, C.GENDER FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITY, C.GENDER
ORDER BY 1,3
