SELECT BRAND,MODEL,
PRICE,
(SELECT AVG(PRICE) FROM WEBOFFERS) AS ORTALAMA_FIYAT 
FROM WEBOFFERS

SELECT BRAND,MODEL,
PRICE,
AVG(PRICE) OVER() AS ORTALAMA_FIYAT 
FROM WEBOFFERS

SELECT BRAND,MODEL,
PRICE,
MAX(PRICE) OVER() AS MAKSIMUM_FIYAT 
FROM WEBOFFERS,

SELECT BRAND,MODEL,
PRICE,
AVG(PRICE) OVER() AS ORTALAMA_FIYAT,
PRICE - AVG(PRICE) OVER() AS FIYAT_FARKI
FROM WEBOFFERS


SELECT BRAND,MODEL,
PRICE,
SUM(PRICE) OVER() TOPLAM_FÝYAT
FROM WEBOFFERS
WHERE BRAND ='Audi'
AND FUEL ='Benzin'


SELECT BRAND,MODEL,
KM,
COUNT(ID) OVER() AS TOPLAM_ARAC_SAYISI
FROM WEBOFFERS
WHERE KM >= 200000 
AND 
BRAND = 'Tofaþ'
ORDER BY 3 DESC;


SELECT BRAND,MODEL,
PRICE,
SUM(PRICE) OVER() TOPLAM_FÝYAT
FROM WEBOFFERS
WHERE PRICE > AVG(PRICE) OVER() 


SELECT BRAND,MODEL,ORIGIN,
KM,
MAX(KM) OVER() AS MAKS_KM,
AVG(KM) OVER() AS ORT_KM,
MIN(KM) OVER() AS MIN_KM,
KM-AVG(KM) OVER() AS KM_FARK
FROM WEBOFFERS
WHERE SHIFTTYPE = 'Otomatik Vites'



SELECT BRAND,MODEL,ORIGIN,
KM,SHIFTTYPE,
MAX(KM) OVER() AS MAKS_KM,
AVG(KM) OVER() AS ORT_KM,
MIN(KM) OVER() AS MIN_KM,
AVG(KM) OVER() - KM AS KM_FARK
FROM WEBOFFERS
WHERE SHIFTTYPE IN( 'Otomatik Vites','Yarý Otomatik Vites')
ORDER BY KM DESC;


