
SELECT ID,TITLE,
PRICE,
MAX(PRICE) OVER (PARTITION BY MODEL) AS MAKSIMUM_FIYAT
FROM WEBOFFERS

SELECT
BRAND,
RAISEPRICE,
MIN(RAISEPRICE) OVER(PARTITION BY BRAND) AS MIN_FIYAT,
ROUND(AVG(RAISEPRICE) OVER(PARTITION BY BRAND),0) ORTALAMA_FIYAT,
MAX(RAISEPRICE) OVER(PARTITION BY BRAND) MAX_FIYAT
FROM WEBOFFERS

SELECT
ID,
YEAR_,
COUNT(ID) OVER (PARTITION BY YEAR_) AS YIL_TOPLAM_ARAC
FROM WEBOFFERS
ORDER BY 3 DESC;


SELECT ID,
BRAND,
CASETYPE,
COUNT(ID) OVER (PARTITION BY BRAND) KRITER_TOPLAM_ARAC
FROM WEBOFFERS
WHERE CASETYPE = 'Sedan'
AND
KM <= 50000
AND YEAR_ = '2016'


SELECT ID,
BRAND,
CASETYPE,
KM,
AVG(KM) OVER (PARTITION BY BRAND,CASETYPE) AS ORTALAMA_KM
FROM WEBOFFERS
ORDER BY ORTALAMA_KM DESC

SELECT ID,
BRAND,
YEAR_,
COUNT(ID) OVER(PARTITION BY YEAR_) YIL_ADET,
AVG(PRICE) OVER(PARTITION BY BRAND) ORTALAMA_FIYAT
FROM WEBOFFERS


